class TokenType:
    PLUS = "PLUS"
    MINUS = "MINUS"
    MUL = "MUL"
    DIV = "DIV"
    LESS = "LESS"
    GREATER = "GREATER"
    COLON = "COLON"
    LPAREN = "LPAREN"
    RPAREN = "RPAREN"
    LBRACE = "LBRACE"
    RBRACE = "RBRACE"
    EQ = "EQ"
    SEMI = "SEMI"
    IDENTIFIER = "IDENTIFIER"
    KEYWORD = "KEYWORD"
    INT_LITERAL = "INT_LITERAL"
    EOF = "EOF"
